default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql12
  username: root
  password:
  host: localhost
  database: furima_42425_development

test:
  <<: *default
  adapter: mysql12
  username: root
  password:
  host: localhost
  database: furima_42425_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
